#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --partition=gpu_a100
#SBATCH --time=03:00:00
#SBATCH --cpus-per-task=8
#SBATCH --job-name=finetune_model
#SBATCH --output=logs/%x/%j.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd ~/Repo_Combined/banyan

source activate banyan

# Keep most of Banyan frozen, only train projection head
python src/train_retrieval.py \
    --pretrained_path checkpoints/en.pt \
    --train_path data/msmarco/prepared_data/train.jsonl \
    --dev_path data/msmarco/prepared_data/val.jsonl \
    --use_projection \
    --projection_dim 128 \
    --freeze_embeddings \
    --freeze_composition \
    --batch_size 256 \
    --lr 1e-3 \
    --epochs 5 \
    --save_path checkpoints/banyan_retrieval_frozen.pt