#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --partition=gpu_a100
#SBATCH --time=00:30:00
#SBATCH --cpus-per-task=8
#SBATCH --job-name=retrieval_finetune
#SBATCH --output=logs/%x/%j.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd ~/Repo_Combined/banyan

source activate banyan

python src/retrieval_finetune.py \
    --vanilla checkpoints/en.pt \
    --finetuned checkpoints/banyan_retrieval_full.pt \
    --datasets data/arguana,data/quora,data/nfcorpus,data/scifact