#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --partition=gpu_a100
#SBATCH --time=03:00:00
#SBATCH --cpus-per-task=8
#SBATCH --job-name=train_model
#SBATCH --output=logs/%x/%j.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd ~/Repo_Combined/banyan

source activate banyan

python src/train.py \
  --train_path data/en_train.txt \
  --dev_path data/en_dev.txt \
  --save_path checkpoints/en.pt
