#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --partition=gpu_a100
#SBATCH --time=5:00:00
#SBATCH --cpus-per-task=8
#SBATCH --job-name=finetune_roberta
#SBATCH --output=logs/%x/%j.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate roberta_env


python finetune_retrieval.py \
  --model_path checkpoints/checkpoint-200000 \
  --train_data ~/Repo_Combined/banyan/data/msmarco/prepared_data/train.jsonl \
  --val_data ~/Repo_Combined/banyan/data/msmarco/prepared_data/val.jsonl \
  --output_dir checkpoints/roberta_finetuned \
  --batch_size 32 \
  --learning_rate 2e-5 \
  --epochs 3 \
  --temperature 0.05 \
  --eval_steps 500