#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=load.py
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

# Your job starts in the directory where you call sbatch
# cd $../part2
# Activate your environment
source activate banyan
# Run your code
srun python rnd_baseline.py 