#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --partition=gpu_a100
#SBATCH --time=00:25:00
#SBATCH --cpus-per-task=8
#SBATCH --job-name=train_sent2vec
#SBATCH --output=logs/%x/%j.out

module purge
module load 2024
module load Anaconda3/2024.06-1
source activate base

./fasttext sent2vec -input ~/Repo_Combined/banyan/data/en_train.txt -output checkpoints/sent2vec_en -minCount 5 -lr 0.2 -dim 256 -epoch 13 -minCountLabel 8 -neg 10 -wordNgrams 1 -loss ns -dropoutK 0 -thread 48