#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --partition=gpu_a100
#SBATCH --time=03:00:00
#SBATCH --cpus-per-task=8
#SBATCH --job-name=eval_retrieval
#SBATCH --output=logs/%x/%j.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd ~/self-strae-original

source activate banyan2

# Evaluate on ArguAna
echo "Evaluating..."
python src/evaluate_retrieval.py \
  --checkpoint_path checkpoints/ensub.pt \