#!/bin/bash
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --partition=gpu_a100
#SBATCH --time=05:00:00
#SBATCH --cpus-per-task=8
#SBATCH --job-name=train_self_strae
#SBATCH --output=logs/%x/%j.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd ~/self-strae-original

source base

python src/train.py \
  --train_path data/en_train_10m.txt \
  --dev_path data/en_dev.txt \
  --save_path checkpoints/ensub.pt \
  --loss_type CECO \
  --lr 1e-3

